export type Theme = {
  name: string
  background: string
  foreground: string
  cursor: string
  selectionBackground: string
  selectionForeground: string
  ansi: string[]
}

export const defaultTheme: Theme = {
  name: "My theme",
  background: "#1e1e2e",
  foreground: "#cdd6f4",
  cursor: "#f5e0dc",
  selectionBackground: "#585b70",
  selectionForeground: "#cdd6f4",
  ansi: [
    "#82859f", "#f38ba8", "#a6e3a1", "#f9e2af", "#89b4fa", "#f5c2e7", "#94e2d5", "#bac2de",
    "#9295a9", "#f38ba8", "#a6e3a1", "#f9e2af", "#89b4fa", "#f5c2e7", "#94e2d5", "#a6adc8"
  ]
}

export const colorNames = [
  "Black (ANSI 0)", "Error (red)", "Success (green)", "Warning (yellow)",
  "Directory / path (blue)", "Git branch (magenta)", "Link / information (cyan)", "Primary text (white)",
  "Bright black (ANSI 8)", "Bright error (bright red)", "Bright success (bright green)", "Bright warning (bright yellow)",
  "Bright directory (bright blue)", "Bright Git branch (bright magenta)", "Bright link (bright cyan)", "Bright text (bright white)"
]

export const slugify = (value: string) => value.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "terminal-theme"

const quoted = (value: string) => JSON.stringify(value)
const paletteLines = (theme: Theme, style: "equals" | "space" = "equals") => theme.ansi.map((color, i) => style === "equals" ? `color${i} = ${color}` : `color${i} ${color}`).join("\n")
const rgb = (hex: string) => [1, 3, 5].map(index => Number.parseInt(hex.slice(index, index + 2), 16))
const konsoleColor = (hex: string) => rgb(hex).join(",")
const iTermColor = (name: string, hex: string) => {
  const [red, green, blue] = rgb(hex).map(value => (value / 255).toFixed(6))
  return `  <key>${name}</key><dict><key>Color Space</key><string>sRGB</string><key>Red Component</key><real>${red}</real><key>Green Component</key><real>${green}</real><key>Blue Component</key><real>${blue}</real></dict>`
}
const ansiNames = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
const namedPalette = (theme: Theme, offset = 0) => ansiNames.map((name, index) => `${name}: ${theme.ansi[index + offset]}`).join("\n")
const shellPalette = (theme: Theme) => theme.ansi.map(color => `'${color}'`).join(", ")
const rgbCsv = (hex: string) => rgb(hex).join(",")
const oscSequence = (theme: Theme): [string, string][] => [
  ["10", theme.foreground],
  ["11", theme.background],
  ["12", theme.cursor],
  ...theme.ansi.map((color, index): [string, string] => [`4;${index}`, color])
]

export type ExportTarget = { id: string; label: string; filename: (slug: string) => string; generate: (theme: Theme) => string }

export const exports: ExportTarget[] = [
  { id: "kitty", label: "Kitty (.conf)", filename: s => `${s}.conf`, generate: t => `# ${t.name}\nforeground ${t.foreground}\nbackground ${t.background}\ncursor ${t.cursor}\nselection_foreground ${t.selectionForeground}\nselection_background ${t.selectionBackground}\n${paletteLines(t, "space")}` },
  { id: "wezterm", label: "WezTerm (.toml)", filename: s => `${s}.toml`, generate: t => `[metadata]\nname = ${quoted(t.name)}\n\n[colors]\nforeground = ${quoted(t.foreground)}\nbackground = ${quoted(t.background)}\ncursor_bg = ${quoted(t.cursor)}\nselection_fg = ${quoted(t.selectionForeground)}\nselection_bg = ${quoted(t.selectionBackground)}\nansi = [${t.ansi.slice(0, 8).map(quoted).join(", ")}]\nbrights = [${t.ansi.slice(8).map(quoted).join(", ")}]\n` },
  { id: "alacritty", label: "Alacritty (.toml)", filename: s => `${s}.toml`, generate: t => `[colors.primary]\nbackground = ${quoted(t.background)}\nforeground = ${quoted(t.foreground)}\n\n[colors.cursor]\ncursor = ${quoted(t.cursor)}\ntext = ${quoted(t.background)}\n\n[colors.selection]\ntext = ${quoted(t.selectionForeground)}\nbackground = ${quoted(t.selectionBackground)}\n\n[colors.normal]\n${["black","red","green","yellow","blue","magenta","cyan","white"].map((n,i) => `${n} = ${quoted(t.ansi[i])}`).join("\n")}\n\n[colors.bright]\n${["black","red","green","yellow","blue","magenta","cyan","white"].map((n,i) => `${n} = ${quoted(t.ansi[i+8])}`).join("\n")}\n` },
  { id: "windows-terminal", label: "Windows Terminal (.json)", filename: s => `${s}.json`, generate: t => JSON.stringify({ schemes: [{ name: t.name, background: t.background, foreground: t.foreground, cursorColor: t.cursor, selectionBackground: t.selectionBackground, black: t.ansi[0], red: t.ansi[1], green: t.ansi[2], yellow: t.ansi[3], blue: t.ansi[4], purple: t.ansi[5], cyan: t.ansi[6], white: t.ansi[7], brightBlack: t.ansi[8], brightRed: t.ansi[9], brightGreen: t.ansi[10], brightYellow: t.ansi[11], brightBlue: t.ansi[12], brightPurple: t.ansi[13], brightCyan: t.ansi[14], brightWhite: t.ansi[15] }] }, null, 2) + "\n" },
  { id: "iterm2", label: "iTerm2 (.itermcolors)", filename: s => `${s}.itermcolors`, generate: t => `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0"><dict>\n${iTermColor("Background Color", t.background)}\n${iTermColor("Foreground Color", t.foreground)}\n${iTermColor("Cursor Color", t.cursor)}\n${iTermColor("Selection Color", t.selectionBackground)}\n${t.ansi.map((color, index) => iTermColor(`Ansi ${index} Color`, color)).join("\n")}\n</dict></plist>\n` },
  { id: "ghostty", label: "Ghostty (theme)", filename: s => s, generate: t => `# ${t.name}\nbackground = ${t.background}\nforeground = ${t.foreground}\ncursor-color = ${t.cursor}\nselection-background = ${t.selectionBackground}\nselection-foreground = ${t.selectionForeground}\n${t.ansi.map((c, i) => `palette = ${i}=${c}`).join("\n")}\n` },
  { id: "konsole", label: "Konsole (.colorscheme)", filename: s => `${s}.colorscheme`, generate: t => `[General]\nDescription=${t.name}\nOpacity=1\n\n[Background]\nColor=${konsoleColor(t.background)}\n\n[Foreground]\nColor=${konsoleColor(t.foreground)}\n\n[Cursor]\nColor=${konsoleColor(t.cursor)}\n\n${t.ansi.slice(0, 8).map((color, index) => `[Color${index}]\nColor=${konsoleColor(color)}`).join("\n\n")}\n\n${t.ansi.slice(8).map((color, index) => `[Color${index}Intense]\nColor=${konsoleColor(color)}`).join("\n\n")}\n` }
  ,{ id: "contour", label: "Contour (.yml)", filename: s => `${s}-contour.yml`, generate: t => `# ${t.name}\n# Merge under color_schemes in ~/.config/contour/contour.yml\ncolor_schemes:\n  ${slugify(t.name)}:\n    default:\n      background: ${quoted(t.background)}\n      foreground: ${quoted(t.foreground)}\n    cursor:\n      default: ${quoted(t.cursor)}\n      text: CellBackground\n    selection:\n      foreground: ${quoted(t.selectionForeground)}\n      background: ${quoted(t.selectionBackground)}\n    normal:\n${ansiNames.map((name, index) => `      ${name}: ${quoted(t.ansi[index])}`).join("\n")}\n    bright:\n${ansiNames.map((name, index) => `      ${name}: ${quoted(t.ansi[index + 8])}`).join("\n")}\n` }
  ,{ id: "foot", label: "foot (.ini)", filename: s => `${s}.ini`, generate: t => `[colors]\nbackground=${t.background.slice(1)}\nforeground=${t.foreground.slice(1)}\ncursor=${t.cursor.slice(1)}\nselection-foreground=${t.selectionForeground.slice(1)}\nselection-background=${t.selectionBackground.slice(1)}\n${t.ansi.slice(0, 8).map((color, index) => `regular${index}=${color.slice(1)}`).join("\n")}\n${t.ansi.slice(8).map((color, index) => `bright${index}=${color.slice(1)}`).join("\n")}\n` }
  ,{ id: "rio", label: "Rio (.toml)", filename: s => `${s}.toml`, generate: t => `[colors]\nbackground = ${quoted(t.background)}\nforeground = ${quoted(t.foreground)}\ncursor = ${quoted(t.cursor)}\nselection-background = ${quoted(t.selectionBackground)}\nselection-foreground = ${quoted(t.selectionForeground)}\n${ansiNames.map((name, index) => `${name} = ${quoted(t.ansi[index])}`).join("\n")}\n${ansiNames.map((name, index) => `light-${name} = ${quoted(t.ansi[index + 8])}`).join("\n")}\n` }
  ,{ id: "hyper", label: "Hyper (.hyper.js)", filename: s => `${s}.hyper.js`, generate: t => `// Add this object inside config in .hyper.js\nmodule.exports = {\n  config: {\n    foregroundColor: ${quoted(t.foreground)},\n    backgroundColor: ${quoted(t.background)},\n    cursorColor: ${quoted(t.cursor)},\n    cursorAccentColor: ${quoted(t.background)},\n    selectionColor: ${quoted(t.selectionBackground)},\n    colors: {\n${ansiNames.map((name, index) => `      ${name}: ${quoted(t.ansi[index])},\n      light${name[0].toUpperCase()}${name.slice(1)}: ${quoted(t.ansi[index + 8])}`).join(",\n")}\n    }\n  }\n}\n` }
  ,{ id: "tabby", label: "Tabby (.yaml)", filename: s => `${s}.yaml`, generate: t => `# Add under terminal.customColorSchemes in Tabby's config.yaml\n- name: ${quoted(t.name)}\n  foreground: ${quoted(t.foreground)}\n  background: ${quoted(t.background)}\n  cursor: ${quoted(t.cursor)}\n  cursorAccent: ${quoted(t.background)}\n  selection: ${quoted(t.selectionBackground)}\n  selectionForeground: ${quoted(t.selectionForeground)}\n  colors:\n${t.ansi.map(color => `    - ${quoted(color)}`).join("\n")}\n` }
  ,{ id: "warp", label: "Warp (.yaml)", filename: s => `${s}.yaml`, generate: t => `name: ${quoted(t.name)}\naccent: ${t.cursor}\ncursor: ${t.cursor}\nbackground: ${t.background}\nforeground: ${t.foreground}\ndetails:\n  darker: ${t.background}\n  lighter: ${t.foreground}\nterminal_colors:\n  normal:\n${namedPalette(t).split("\n").map(line => `    ${line}`).join("\n")}\n  bright:\n${namedPalette(t, 8).split("\n").map(line => `    ${line}`).join("\n")}\n` }
  ,{ id: "terminal-app", label: "Terminal.app (installation guide .md)", filename: s => `${s}-terminal-app.md`, generate: t => `# ${t.name} — Terminal.app\n\nTerminal.app imports .terminal profiles, but Apple stores each color in a specific binary format.\n\n1. Open Terminal > Settings > Profiles and create a profile.\n2. In the Text tab, set text to ${t.foreground}, background to ${t.background}, and cursor to ${t.cursor}.\n3. In the Colors tab, enter the ANSI palette:\n\n${t.ansi.map((color, index) => `- ANSI ${index}: ${color}`).join("\n")}\n\nSelection: background ${t.selectionBackground}, text ${t.selectionForeground}.\nThen export the profile from Terminal to generate its native .terminal file.\n` }
  ,{ id: "tilix", label: "Tilix (script .sh)", filename: s => `${s}-tilix.sh`, generate: t => `#!/usr/bin/env bash\n# Applies the palette to Tilix's current default profile.\nset -eu\nprofile=$(gsettings get com.gexperts.Tilix.ProfilesList default | tr -d \"'\")\npath=\"/com/gexperts/Tilix/profiles/$profile/\"\ngsettings set com.gexperts.Tilix.Profile:\"$path\" use-theme-colors false\ngsettings set com.gexperts.Tilix.Profile:\"$path\" background-color '${t.background}'\ngsettings set com.gexperts.Tilix.Profile:\"$path\" foreground-color '${t.foreground}'\ngsettings set com.gexperts.Tilix.Profile:\"$path\" palette \"[${shellPalette(t)}]\"\n` }
  ,{ id: "terminator", label: "Terminator (.config)", filename: s => `${s}-terminator.config`, generate: t => `# Merge this profile into ~/.config/terminator/config\n[profiles]\n  [[${slugify(t.name)}]]\n    use_theme_colors = False\n    foreground_color = ${t.foreground}\n    background_color = ${t.background}\n    cursor_color = ${t.cursor}\n    palette = ${t.ansi.join(":")}\n` }
  ,{ id: "gnome-terminal", label: "GNOME Terminal (script .sh)", filename: s => `${s}-gnome-terminal.sh`, generate: t => `#!/usr/bin/env bash\n# Applies the palette to GNOME Terminal's current default profile.\nset -eu\nprofile=$(gsettings get org.gnome.Terminal.ProfilesList default | tr -d \"'\")\npath=\"/org/gnome/terminal/legacy/profiles:/:$profile/\"\nschema=org.gnome.Terminal.Legacy.Profile:\"$path\"\ngsettings set \"$schema\" use-theme-colors false\ngsettings set \"$schema\" foreground-color '${t.foreground}'\ngsettings set \"$schema\" background-color '${t.background}'\ngsettings set \"$schema\" palette \"[${shellPalette(t)}]\"\n` }
  ,{ id: "ptyxis", label: "Ptyxis (.palette)", filename: s => `${s}.palette`, generate: t => `[Palette]\nName=${t.name}\nForeground=${t.foreground}\nBackground=${t.background}\nCursor=${t.cursor}\nSelectionBackground=${t.selectionBackground}\nSelectionForeground=${t.selectionForeground}\n${t.ansi.map((color, index) => `Color${index}=${color}`).join("\n")}\n` }
  ,{ id: "xfce-terminal", label: "Xfce Terminal (.theme)", filename: s => `${s}.theme`, generate: t => `[Scheme]\nName=${t.name}\nColorForeground=${t.foreground}\nColorBackground=${t.background}\nColorCursor=${t.cursor}\nColorSelection=${t.selectionBackground}\nColorPalette=${t.ansi.join(";")}\n` }
  ,{ id: "xterm", label: "xterm (.Xresources)", filename: s => `${s}-xterm.Xresources`, generate: t => `! ${t.name}\nxterm*background: ${t.background}\nxterm*foreground: ${t.foreground}\nxterm*cursorColor: ${t.cursor}\n${t.ansi.map((color, index) => `xterm*color${index}: ${color}`).join("\n")}\n` }
  ,{ id: "urxvt", label: "urxvt / rxvt-unicode (.Xresources)", filename: s => `${s}-urxvt.Xresources`, generate: t => `! ${t.name}\nURxvt*background: ${t.background}\nURxvt*foreground: ${t.foreground}\nURxvt*cursorColor: ${t.cursor}\n${t.ansi.map((color, index) => `URxvt*color${index}: ${color}`).join("\n")}\n` }
  ,{ id: "putty", label: "PuTTY (.reg)", filename: s => `${s}-putty.reg`, generate: t => `Windows Registry Editor Version 5.00\n\n; Import this after creating a PuTTY saved session named ${t.name}.\n[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\${encodeURIComponent(t.name)}]\n\"Colour0\"=\"${rgbCsv(t.foreground)}\"\n\"Colour1\"=\"${rgbCsv(t.foreground)}\"\n\"Colour2\"=\"${rgbCsv(t.background)}\"\n\"Colour3\"=\"${rgbCsv(t.background)}\"\n\"Colour5\"=\"${rgbCsv(t.cursor)}\"\n${t.ansi.flatMap((color, index) => [`\"Colour${index * 2 + 6}\"=\"${rgbCsv(color)}\"`, `\"Colour${index * 2 + 7}\"=\"${rgbCsv(color)}\"`]).join("\n")}\n` }
  ,{ id: "mobaxterm", label: "MobaXterm (.ini)", filename: s => `${s}-MobaXterm.ini`, generate: t => `[Colors]\nDefaultColorScheme=4\nBlack=${rgbCsv(t.ansi[0])}\nBoldBlack=${rgbCsv(t.ansi[8])}\nRed=${rgbCsv(t.ansi[1])}\nBoldRed=${rgbCsv(t.ansi[9])}\nGreen=${rgbCsv(t.ansi[2])}\nBoldGreen=${rgbCsv(t.ansi[10])}\nYellow=${rgbCsv(t.ansi[3])}\nBoldYellow=${rgbCsv(t.ansi[11])}\nBlue=${rgbCsv(t.ansi[4])}\nBoldBlue=${rgbCsv(t.ansi[12])}\nMagenta=${rgbCsv(t.ansi[5])}\nBoldMagenta=${rgbCsv(t.ansi[13])}\nCyan=${rgbCsv(t.ansi[6])}\nBoldCyan=${rgbCsv(t.ansi[14])}\nWhite=${rgbCsv(t.ansi[7])}\nBoldWhite=${rgbCsv(t.ansi[15])}\nForegroundColour=${rgbCsv(t.foreground)}\nBackgroundColour=${rgbCsv(t.background)}\nCursorColour=${rgbCsv(t.cursor)}\n` }
  ,{ id: "securecrt", label: "SecureCRT (installation guide .md)", filename: s => `${s}-securecrt.md`, generate: t => `# ${t.name} — SecureCRT\n\nIn Global Options > Terminal > Appearance > Advanced, create a Color Scheme, then an ANSI Color Palette with the same name.\n\n- Text: ${t.foreground}\n- Background: ${t.background}\n- Cursor: ${t.cursor}\n- Selection: ${t.selectionBackground}\n\nANSI palette (decimal RGB):\n${t.ansi.map((color, index) => `- ${index}: ${rgbCsv(color)}`).join("\n")}\n\nApply this scheme in Session Options > Terminal > Appearance.\n` }
  ,{ id: "bash-zsh", label: "Bash / Zsh (.sh)", filename: s => `${s}.sh`, generate: t => `# ${t.name} — paste into ~/.bashrc or ~/.zshrc\n_terminal_theme_studio() {\n${oscSequence(t).map(([code, color]) => `  printf '\\033]${code};%s\\033\\\\' "${color}"`).join("\n")}\n}\n[ -n "$PS1" ] && _terminal_theme_studio\n` }
  ,{ id: "fish", label: "Fish (config.fish)", filename: () => "config.fish", generate: t => `# ${t.name} — paste into ~/.config/fish/config.fish\nfunction _terminal_theme_studio\n${oscSequence(t).map(([code, color]) => `    printf '\\033]${code};%s\\033\\\\' "${color}"`).join("\n")}\nend\nstatus is-interactive; and _terminal_theme_studio\n` }
  ,{ id: "nushell", label: "Nushell (config.nu)", filename: () => "config.nu", generate: t => `# ${t.name} — paste into config.nu (find it with \`$nu.config-path\`)\ndef _terminal_theme_studio [] {\n${oscSequence(t).map(([code, color]) => `    print -n $"(ansi -o '${code};${color}')(ansi st)"`).join("\n")}\n}\n_terminal_theme_studio\n` }
]

const installationSteps = (target: ExportTarget, theme: Theme) => {
  const filename = target.filename(slugify(theme.name))
  switch (target.id) {
    case "alacritty": return `Alacritty loads color themes from separate files that you \`import\` into its main configuration.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.config/alacritty/themes\nmv ~/Downloads/${filename} ~/.config/alacritty/themes/\n\`\`\`\n\n1. Create a themes folder if you don't already have one: \`mkdir -p ~/.config/alacritty/themes\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Open \`~/.config/alacritty/alacritty.toml\` and add (or extend) an \`import\` line: \`import = ["~/.config/alacritty/themes/${filename}"]\`.\n4. Save the file and restart Alacritty — it re-reads the config on launch, and recent versions also hot-reload on save.\n5. Check it worked: the window background, text, and \`ls\`/prompt colors should now match the theme.`
    case "bash-zsh": return `This file is a shell script that repaints your terminal's palette using escape sequences — it doesn't create a "theme" file the terminal reads later, it just needs to run every time you open a shell.\n\nCopy-paste (assumes the file is in \`~/Downloads\`; pick your shell):\n\n\`\`\`bash\n# Bash\ncat ~/Downloads/${filename} >> ~/.bashrc && source ~/.bashrc\n# Zsh\ncat ~/Downloads/${filename} >> ~/.zshrc && source ~/.zshrc\n\`\`\`\n\n1. Open (or create) your shell's startup file: \`~/.bashrc\` for Bash, or \`~/.zshrc\` for Zsh. If you're not sure which shell you use, run \`echo $SHELL\`.\n2. Open the downloaded \`${filename}\` and copy its entire content.\n3. Paste it at the very end of \`~/.bashrc\` or \`~/.zshrc\`, then save the file.\n4. Apply it without restarting: run \`source ~/.bashrc\` (or \`source ~/.zshrc\`). Alternatively, just close the terminal and open a new one — the startup file runs automatically for every new interactive shell.\n5. Check it worked: your prompt's text, background, and colors (e.g. from \`ls\` or \`grep --color\`) should now match the theme. If nothing changed, your terminal emulator may not support OSC color sequences — this method changes colors at the shell level, not the emulator's own theme file, so it depends on the emulator honoring these codes (most modern ones do: xterm, GNOME Terminal, kitty, iTerm2, Ghostty…).\n\nNote: the script only runs in *interactive* shells (guarded by \`[ -n "$PS1" ]\`), so it won't interfere with non-interactive scripts, cron jobs, or \`scp\`/\`rsync\` sessions that also read \`.bashrc\`.`
    case "fish": return `This file redefines your terminal's palette using escape sequences, written in Fish's own syntax (Fish doesn't understand Bash syntax like \`export VAR=value\`).\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.config/fish\ncat ~/Downloads/${filename} >> ~/.config/fish/config.fish\nsource ~/.config/fish/config.fish\n\`\`\`\n\n1. Locate Fish's startup file at \`~/.config/fish/config.fish\`. If the \`fish\` folder doesn't exist yet, create it first: \`mkdir -p ~/.config/fish\`.\n2. Open the downloaded \`${filename}\` and copy its entire content.\n3. Paste it at the end of \`~/.config/fish/config.fish\` (create the file if it doesn't exist), then save.\n4. Apply it without restarting: run \`source ~/.config/fish/config.fish\`. Or simply open a new terminal tab/window — Fish reads this file automatically at the start of every interactive session.\n5. Check it worked: your prompt and command output colors should now match the theme. If nothing happens, confirm your terminal emulator supports OSC color sequences (most do — xterm, kitty, iTerm2, Ghostty, GNOME Terminal, etc.).\n\nNote: the last line only runs the theme function when the shell is interactive (\`status is-interactive\`), so scripts run by Fish in the background are unaffected.`
    case "nushell": return `This file redefines your terminal's palette using Nushell's built-in \`ansi\` command to emit the escape sequences, since Nushell doesn't use \`printf\`/\`echo -e\` the way Bash does.\n\nCopy-paste — append the file (assumes it's in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.config/nushell\ncat ~/Downloads/${filename} >> ~/.config/nushell/config.nu\n\`\`\`\n\nThen reload it from inside Nushell:\n\n\`\`\`nu\nsource $nu.config-path\n\`\`\`\n\n1. Find your Nushell config file by running \`$nu.config-path\` inside Nushell — this prints the full path (usually \`~/.config/nushell/config.nu\` on Linux/macOS).\n2. Open the downloaded \`${filename}\` and copy its entire content.\n3. Open your \`config.nu\` in a text editor, paste the content at the end, then save.\n4. Apply it without restarting: run \`source $nu.config-path\` inside Nushell (adjust to the actual path if needed). Or just close and reopen your terminal — \`config.nu\` is read automatically when Nushell starts.\n5. Check it worked: your prompt and command output colors should now reflect the theme. If nothing changes, verify your terminal emulator supports OSC color sequences (xterm, kitty, iTerm2, Ghostty, GNOME Terminal, and most others do).\n\nNote: unlike the Bash/Zsh and Fish versions, this script has no interactive-shell guard, since \`config.nu\` is only ever loaded by interactive Nushell sessions.`
    case "contour": return `Contour keeps *all* of its settings — window options, profiles, and colors — in one YAML file called \`contour.yml\`. There is no separate "themes folder": a theme is just a named block of colors that lives inside this file. Understanding two ideas makes the rest easy.\n\n**Idea 1 — defining vs. applying.** Under the top-level \`color_schemes:\` key you *define* palettes and give each one a name. Under \`profiles:\` you *apply* one by writing its name next to \`colors:\`. Defining a palette does nothing on its own — a profile has to point at it. The downloaded file contains one palette named \`${slugify(theme.name)}\`.\n\n**Idea 2 — indentation is the structure.** YAML has no braces or brackets; nesting is expressed purely by leading spaces (always spaces, never tabs). \`background\` is "inside" the palette because it sits two levels indented under it. If you paste a block at the wrong indentation, Contour reads it as belonging somewhere else — this is the single most common mistake, so keep the exact spacing from the file.\n\nSteps:\n\n1. Locate \`contour.yml\`. On Linux/macOS it's at \`~/.config/contour/contour.yml\`; on Windows it's at \`%LocalAppData%\\contour\\contour.yml\`. If it isn't there yet, just launch Contour once — it writes a fully-commented default file the first time it runs.\n2. Open the downloaded \`${filename}\` next to it. Everything below the two comment lines is your palette: the \`${slugify(theme.name)}:\` line and all the color lines indented beneath it.\n3. In \`contour.yml\`, find the line that reads \`color_schemes:\`. Copy your \`${slugify(theme.name)}:\` block (the name line plus everything indented under it) and paste it so that \`${slugify(theme.name)}:\` sits one indentation level *inside* \`color_schemes:\`, lined up with the other scheme names already there. If your file has no \`color_schemes:\` key at all, add one at the top level and put the block under it.\n4. Now apply it. Under \`profiles:\` find the profile you use (the default is usually named \`main\`) and set its \`colors:\` value to \`${slugify(theme.name)}\` — for example \`colors: ${slugify(theme.name)}\`. This is the line that actually switches the palette on; without it the theme is defined but unused.\n5. Save the file. Contour watches \`contour.yml\` and reloads live, so your open windows should recolor instantly. If they don't, open a new window (or fully quit and relaunch) to force a reload.\n6. Check it worked: the window background, text, cursor, and the 16 ANSI colors (run \`ls\` in a colorful folder, or \`echo\` some colored text) should now match the theme. If nothing changed, the usual causes are: the \`colors:\` line still names the old scheme, the pasted block is indented one step too far or too shallow, or a tab slipped in among the spaces — re-check those three first.`
    case "foot": return `foot doesn't support importing separate theme files — its colors live directly inside its own configuration file, so you merge the generated section in rather than pointing to it.\n\n1. Open the downloaded \`${filename}\` and copy its \`[colors]\` section.\n2. Open \`~/.config/foot/foot.ini\` (create it if it doesn't exist yet).\n3. If a \`[colors]\` section already exists, replace its contents with the copied one; otherwise paste the whole section in.\n4. Save the file.\n5. Open a new foot window — foot reads \`foot.ini\` at startup, so existing windows keep the old colors until closed and reopened.\n6. Check it worked: background, text, and the 16-color palette (try \`ls\` in a colorful directory) should match the theme.`
    case "ghostty": return `Ghostty loads named themes from a dedicated folder, then you select one by name in its config.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.config/ghostty/themes\nmv ~/Downloads/${filename} ~/.config/ghostty/themes/\n\`\`\`\n\n1. Create the themes folder if needed: \`mkdir -p ~/.config/ghostty/themes\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Open \`~/.config/ghostty/config\` and add the line \`theme = ${slugify(theme.name)}\` (this must match the filename you just copied in).\n4. Save the file and restart Ghostty to pick up the new config.\n5. Check it worked: the window background, foreground, and palette colors should now match the theme.`
    case "gnome-terminal": return `GNOME Terminal keeps its color settings in the desktop's configuration database (dconf/gsettings) rather than in a theme file, so the download is a small script that writes those settings for you instead of a file GNOME Terminal reads directly.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nchmod +x ~/Downloads/${filename}\n~/Downloads/${filename}\n\`\`\`\n\n1. Save the downloaded \`${filename}\` somewhere convenient, e.g. your Downloads folder.\n2. Open a terminal and make the script executable: \`chmod +x ${filename}\`.\n3. Run it: \`./${filename}\`. It detects your current default profile and overwrites its colors.\n4. Close every open GNOME Terminal window, then open a new one — running windows don't pick up the change live.\n5. Check it worked: the background, text, and palette colors should now match the theme. If you use multiple profiles, note this script only updates the *default* one.`
    case "hyper": return `Hyper is configured through a single JavaScript file, so instead of a standalone theme file you get a snippet to merge into it.\n\n1. Open the downloaded \`${filename}\` and copy its content — it's a \`config\` object with color settings.\n2. Open Hyper's own configuration file, \`~/.hyper.js\` (open it from Hyper's menu if you're not sure where it lives).\n3. Inside that file, find the \`config: { ... }\` object and merge in the copied properties (\`foregroundColor\`, \`backgroundColor\`, \`colors\`, etc.), replacing any that already exist.\n4. Save \`.hyper.js\`.\n5. Restart Hyper, or trigger a reload if your version supports live-reloading config changes.\n6. Check it worked: the window and text colors should now match the theme.`
    case "iterm2": return `iTerm2 stores color schemes as importable presets, kept separate from your actual profiles until you apply one.\n\n1. Open iTerm2 and go to Settings (or Preferences) > Profiles > Colors.\n2. Click Color Presets… in the bottom-right, then Import….\n3. In the file picker, select the downloaded \`${filename}\`.\n4. The preset is now available but not yet active — open Color Presets… again and select it by name (\`${theme.name}\`) to apply it to the current profile.\n5. Repeat step 4 for any other profile you want themed, since presets apply per-profile.\n6. Check it worked: the profile's background, text, and ANSI colors (visible in the same Colors tab) should now match the theme.`
    case "kitty": return `kitty loads named color themes from an includes folder, referenced from its main config file.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.config/kitty/themes\nmv ~/Downloads/${filename} ~/.config/kitty/themes/\n\`\`\`\n\n1. Create the themes folder if it doesn't exist: \`mkdir -p ~/.config/kitty/themes\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Open \`~/.config/kitty/kitty.conf\` and add the line \`include themes/${filename}\` (remove or comment out any previous \`include themes/...\` line so themes don't conflict).\n4. Save the file.\n5. Restart kitty, or reload the config live with \`ctrl+shift+F5\` (or your configured reload shortcut) if enabled.\n6. Check it worked: the background, foreground, and 16-color palette should now match the theme.`
    case "konsole": return `Konsole reads color schemes from a shared per-user folder and lists them by name in its profile settings.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.local/share/konsole\nmv ~/Downloads/${filename} ~/.local/share/konsole/\n\`\`\`\n\n1. Create the folder if it doesn't exist: \`mkdir -p ~/.local/share/konsole\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. In Konsole, open Settings > Edit Current Profile > Appearance.\n4. In the color scheme list, select \`${theme.name}\` — it should appear automatically since Konsole scans that folder.\n5. Click Apply / OK to save the profile.\n6. Check it worked: the window background, text, and palette should now match the theme. If it doesn't appear in the list, double-check the file landed directly in \`~/.local/share/konsole/\` (not a subfolder).`
    case "mobaxterm": return `MobaXterm keeps all of its settings, including colors, in a single shared \`.ini\` file — there's no per-theme import, so you merge the relevant section in by hand.\n\n1. Locate your \`MobaXterm.ini\` (in the same folder as the MobaXterm executable, or under Settings > Configuration > General > Persistent home directory).\n2. Make a backup copy of it before editing, in case something needs reverting.\n3. Open the downloaded \`${filename}\` and copy its \`[Colors]\` section.\n4. Open \`MobaXterm.ini\` in a text editor and replace its existing \`[Colors]\` section with the copied one (or add it if missing).\n5. Save the file and restart MobaXterm completely (it must not be running while you edit the file, or your changes may be overwritten on exit).\n6. Check it worked: session windows should now use the new background, text, and palette colors.`
    case "ptyxis": return `Ptyxis (GNOME's newer terminal) loads color palettes from a per-user folder, similar to Konsole.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.local/share/org.gnome.Ptyxis/palettes\nmv ~/Downloads/${filename} ~/.local/share/org.gnome.Ptyxis/palettes/\n\`\`\`\n\n1. Create the palettes folder if it doesn't exist: \`mkdir -p ~/.local/share/org.gnome.Ptyxis/palettes\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Restart Ptyxis so it picks up the new palette (it scans this folder on startup).\n4. Open Ptyxis' profile preferences and select \`${theme.name}\` from the palette list.\n5. Check it worked: the background, text, and palette colors of that profile should now match the theme.`
    case "putty": return `PuTTY stores its settings, including colors, in the Windows Registry per saved session — so colors are imported into a session that must already exist.\n\nCopy-paste (Command Prompt, after saving a session named \`${theme.name}\`; assumes the file is in your Downloads folder):\n\n\`\`\`bat\nreg import "%USERPROFILE%\\Downloads\\${filename}"\n\`\`\`\n\n1. Open PuTTY, enter any host (or leave it blank), and under Session give it the name \`${theme.name}\`, then click Save. This creates the registry entry the import will fill in.\n2. Double-click the downloaded \`${filename}\` and confirm the Registry Editor prompt (or run \`reg import ${filename}\` from a command prompt if you prefer no GUI prompt).\n3. Restart PuTTY.\n4. Open the saved session named \`${theme.name}\` from the session list and click Load, then Open.\n5. Check it worked: the window background, text, and ANSI colors should now match the theme.`
    case "rio": return `Rio loads named themes from a themes folder, referenced by name from its main config.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.config/rio/themes\nmv ~/Downloads/${filename} ~/.config/rio/themes/\n\`\`\`\n\n1. Create the themes folder if it doesn't exist: \`mkdir -p ~/.config/rio/themes\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Open \`~/.config/rio/config.toml\` and add or update the line \`theme = "${slugify(theme.name)}"\` (this must match the filename you copied in, without its extension).\n4. Save the file and restart Rio (or trigger its live-reload if you have it enabled).\n5. Check it worked: the window background, text, and palette should now match the theme.`
    case "securecrt": return `SecureCRT has no theme-file import — colors are entered manually through its settings dialogs, so the download is a step-by-step reference rather than a file it reads directly.\n\n1. Open the downloaded \`${filename}\` — it lists every color value you'll need to type in.\n2. In SecureCRT, go to Global Options > Terminal > Appearance > Advanced (exact menu path varies slightly by version).\n3. Create a new Color Scheme, then a new ANSI Color Palette, and give both the same name so they're easy to find later.\n4. Enter the text, background, cursor, and selection colors from the guide into the corresponding fields.\n5. Enter each of the 16 ANSI palette colors (the guide lists them by index) into the palette editor.\n6. Save, then go to Session Options > Terminal > Appearance and select the scheme you just created for the session you want themed.\n7. Check it worked: reopen that session — its colors should now match the theme.`
    case "tabby": return `Tabby stores custom color schemes as entries in its main YAML config file rather than as separate files.\n\n1. Open the downloaded \`${filename}\` and copy its content — it's a single scheme entry.\n2. Open Tabby's Settings and find Settings > Color Schemes (or edit \`config.yaml\` directly via Settings > Advanced > Edit configuration).\n3. Paste the copied entry under the \`terminal.customColorSchemes\` list in \`config.yaml\` (create that list if it doesn't exist).\n4. Save the configuration — Tabby reloads it automatically.\n5. Open your terminal profile settings and select \`${theme.name}\` from the color scheme dropdown.\n6. Check it worked: the active tab's colors should now match the theme.`
    case "terminal-app": return `macOS Terminal.app stores each profile's colors in Apple's own binary property-list format, which this tool can't generate directly — so instead of a file to import, you get a written guide to re-enter the values by hand.\n\n1. Open the downloaded \`${filename}\` — it lists every color value you'll need.\n2. Open Terminal > Settings (or Preferences) > Profiles, then click the "+" button to create a new profile.\n3. Give the profile a name (e.g. \`${theme.name}\`) so you can find it later.\n4. In the Text tab, set the text color, background color, and cursor color using the values from the guide.\n5. In the Colors tab (or wherever your macOS version exposes ANSI colors), enter each of the 16 ANSI colors listed in the guide.\n6. Optionally, right-click the new profile and choose "Export…" to save it as a reusable \`.terminal\` file.\n7. Set the profile as default if you want new windows to use it automatically.\n8. Check it worked: open a new Terminal window with that profile — its colors should match the theme.`
    case "terminator": return `Terminator keeps every profile in one shared config file, structured as nested INI-like sections, so you merge the generated block into your existing profile list.\n\n1. Open the downloaded \`${filename}\` and copy its \`[[${slugify(theme.name)}]]\` profile block.\n2. Open \`~/.config/terminator/config\` (create it if it doesn't exist — Terminator generates a default one the first time you change any setting in its Preferences UI).\n3. Paste the copied block inside the existing \`[profiles]\` section, alongside any other profiles.\n4. Save the file.\n5. In Terminator, open Preferences > Profiles — the new profile named \`${slugify(theme.name)}\` should appear in the list. Select it for the terminal(s) you want themed.\n6. Restart Terminator to make sure the config is fully reloaded.\n7. Check it worked: the terminal background, text, and palette should now match the theme.`
    case "tilix": return `Tilix, like GNOME Terminal, stores its color settings in the desktop's configuration database rather than in a theme file, so the download is a small script that writes those settings for you.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nchmod +x ~/Downloads/${filename}\n~/Downloads/${filename}\n\`\`\`\n\n1. Save the downloaded \`${filename}\` somewhere convenient.\n2. Open a terminal and make it executable: \`chmod +x ${filename}\`.\n3. Run it: \`./${filename}\`. It detects your current default profile and overwrites its colors.\n4. Open a new Tilix window (existing ones won't refresh automatically).\n5. Check it worked: the background, text, and palette colors should now match the theme. If you use multiple profiles, this script only updates the *default* one.`
    case "urxvt": return `urxvt (rxvt-unicode) reads its colors from the X resources database, a system-wide store shared by several X11 terminal emulators (also used by xterm) — not from a file urxvt reads on its own.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\ncat ~/Downloads/${filename} >> ~/.Xresources\nxrdb -merge ~/.Xresources\n\`\`\`\n\n1. Open the downloaded \`${filename}\` and copy its content.\n2. Open (or create) \`~/.Xresources\` in a text editor and paste the content at the end. If you're replacing a previous urxvt theme, remove the old \`URxvt*\` lines first to avoid conflicts.\n3. Save the file.\n4. Load the updated resources into the X server: run \`xrdb -merge ~/.Xresources\`.\n5. Open a new urxvt window — existing windows keep the colors they started with.\n6. Check it worked: the background, text, and palette should now match the theme. Note this also affects any other application reading the same X resources.`
    case "warp": return `Warp loads custom themes from a per-user themes folder, then you pick one by name in its settings.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.warp/themes\nmv ~/Downloads/${filename} ~/.warp/themes/\n\`\`\`\n\n1. Create the folder if it doesn't exist: \`mkdir -p ~/.warp/themes\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Open Warp's Settings > Appearance > Themes.\n4. Find \`${theme.name}\` in the list (Warp scans the themes folder) and select it.\n5. Restart Warp if the new theme doesn't appear right away.\n6. Check it worked: the window background, text, and palette should now match the theme.`
    case "wezterm": return `WezTerm loads named color schemes from a colors folder, then you reference the scheme by name (or merge its colors) from your Lua configuration.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.config/wezterm/colors\nmv ~/Downloads/${filename} ~/.config/wezterm/colors/\n\`\`\`\n\n1. Create the folder if it doesn't exist: \`mkdir -p ~/.config/wezterm/colors\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Open your WezTerm config (usually \`~/.config/wezterm/wezterm.lua\`) and set \`config.color_scheme = "${theme.name}"\` — WezTerm automatically discovers schemes placed in the \`colors\` folder by that name.\n4. Save the file — WezTerm live-reloads its config by default, so the change should apply immediately without restarting.\n5. Check it worked: the window background, text, and palette should now match the theme.`
    case "windows-terminal": return `Windows Terminal keeps every color scheme in a single JSON settings file, as entries in a shared \`schemes\` array, rather than as separate files.\n\n1. Open Windows Terminal, click the dropdown arrow next to the tabs, and choose Settings.\n2. At the bottom of the Settings sidebar, click "Open JSON file" to edit the raw configuration.\n3. Open the downloaded \`${filename}\` and copy the single scheme object inside it.\n4. In the JSON file, find the \`schemes\` array and paste the copied object as a new entry (make sure it's comma-separated from its neighbors).\n5. Save the JSON file — Windows Terminal watches it and reloads automatically.\n6. Go back to Settings, open the profile you want to theme, and under Appearance select \`${theme.name}\` as its color scheme.\n7. Check it worked: that profile's background, text, and palette should now match the theme.`
    case "xfce-terminal": return `Xfce Terminal loads named color schemes from a per-user folder, but — unlike most terminals here — it only scans that folder once at startup, not on demand.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\nmkdir -p ~/.local/share/xfce4/terminal/colorschemes\nmv ~/Downloads/${filename} ~/.local/share/xfce4/terminal/colorschemes/\n\`\`\`\n\n1. Create the folder if it doesn't exist: \`mkdir -p ~/.local/share/xfce4/terminal/colorschemes\`.\n2. Move the downloaded \`${filename}\` into that folder.\n3. Close every open Xfce Terminal window completely (check no instance is left running).\n4. Reopen Xfce Terminal — this forces it to rescan the colorschemes folder.\n5. Open Edit > Preferences > Appearance (or Colors, depending on version) and select \`${theme.name}\` from the scheme list.\n6. Check it worked: the background, text, and palette should now match the theme. If the scheme doesn't appear, double-check step 3 — a lingering instance is the most common cause.`
    case "xterm": return `xterm reads its colors from the X resources database, a system-wide store shared by several X11 terminal emulators (also used by urxvt) — there's no xterm-specific theme file format.\n\nCopy-paste (assumes the file is in \`~/Downloads\`):\n\n\`\`\`bash\ncat ~/Downloads/${filename} >> ~/.Xresources\nxrdb -merge ~/.Xresources\n\`\`\`\n\n1. Open the downloaded \`${filename}\` and copy its content.\n2. Open (or create) \`~/.Xresources\` in a text editor and paste the content at the end. If you're replacing a previous xterm theme, remove the old \`xterm*\` lines first to avoid conflicts.\n3. Save the file.\n4. Load the updated resources into the X server: run \`xrdb -merge ~/.Xresources\`.\n5. Open a new xterm window — existing windows keep the colors they started with.\n6. Check it worked: the background, text, and palette should now match the theme. Note this also affects any other application reading the same X resources.`
    default: return `Refer to ${target.label} documentation to import or merge \`${filename}\`.`
  }
}

export const installationGuide = (target: ExportTarget, theme: Theme) => `# Install “${theme.name}” in ${target.label}\n\nTheme file: \`${target.filename(slugify(theme.name))}\`.\n\n## Steps\n\n${installationSteps(target, theme)}\n\n> Files are generated locally by Terminal Theme Studio.\n`

export const allInstallationGuide = (theme: Theme) => `# ${theme.name} — Installation guide\n\nThis archive stores each export in \`themes/<emulator>/\`. Follow only the instructions for the emulator you use.\n\n${exports.map(target => `## ${target.label}\n\nFile: \`themes/${target.id}/${target.filename(slugify(theme.name))}\`.\n\n${installationSteps(target, theme)}`).join("\n\n")}\n\n> All files were generated locally by Terminal Theme Studio.\n`
